In [20]:
import re
import nltk
import numpy as np
import pandas as pd
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import metrics

In [21]:
df = pd.read_csv("./Datasets/Combined_dataset.csv", parse_dates=["Date"], index_col="Date")
df

Headlines  Close/Last  \
Date                                                                        
2015-01-02  Apple Loop: iOS 8.1.3 Angers Users, Outlook Ar...     27.3325   
2015-01-05  Apple Watch interest described as &quot;tepid,...     26.5625   
2015-01-06  Apple&quot;s TV Service Delayed: Getting Local...     26.5650   
2015-01-07  Apple Inc. leaks new iPod colors in iTunes 12....     26.9375   
2015-01-08  Nomura Begins Coverage on Apple (AAPL) IBM cou...     27.9725   
...                                                       ...         ...   
2021-05-28  Apple pushes back launch of podcast subscripti...    124.6100   
2021-06-01  TSX nears record high as cannabis, renewables ...    124.2800   
2021-06-02  Exclusive Social Media App Clubhouse Rises In ...    125.0600   
2021-06-03  Two Patents were fulfilled last week as the Ma...    123.5400   
2021-06-04  This Simple Stock Market Strategy Is Winning s...    125.8900   

               Volume      Open      High       Low  Close_difference  Impact  
Date                                                                           
2015-01-02  212575080   27.8475   27.8600   26.8375           -0.2625       0  
2015-01-05  256843520   27.0725   27.1625   26.3525           -0.7700       0  
2015-01-06  262729000   26.6350   26.8575   26.1575            0.0025       1  
2015-01-07  159933400   26.8000   27.0500   26.6737            0.3725       1  
2015-01-08  236675040   27.3075   28.0375   27.1750            1.0350       1  
...               ...       ...       ...       ...               ...     ...  
2021-05-28   71311110  125.5700  125.8000  124.5500           -0.6700       0  
2021-06-01   67637120  125.0800  125.3500  123.9400           -0.3300       0  
2021-06-02   59278860  124.2800  125.2400  124.0500            0.7800       1  
2021-06-03   76229170  124.6800  124.8500  123.1300           -1.5200       0  
2021-06-04   75169340  124.0700  126.1600  123.8500            2.3500       1  

[1595 rows x 8 columns]

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1595 entries, 2015-01-02 to 2021-06-04
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Headlines         1595 non-null   object 
 1   Close/Last        1595 non-null   float64
 2   Volume            1595 non-null   int64  
 3   Open              1595 non-null   float64
 4   High              1595 non-null   float64
 5   Low               1595 non-null   float64
 6   Close_difference  1595 non-null   float64
 7   Impact            1595 non-null   int64  
dtypes: float64(5), int64(2), object(1)
memory usage: 112.1+ KB


In [23]:
cleaned_headlines = []
ps = PorterStemmer()
for i in range(0, len(df)):
  headlines = re.sub('[^a-zA-Z]', ' ', df['Headlines'][i])
  headlines = headlines.lower()
  headlines = headlines.split()
  headlines_stopwords = stopwords.words('english')
  headlines_stopwords.remove('not')
  headlines = [ps.stem(word) for word in headlines if not word in set(headlines_stopwords)]
  headlines = ' '.join(headlines)
  cleaned_headlines.append(headlines)
len(cleaned_headlines)

1595

In [24]:
cv = CountVectorizer(max_features = 20000)
X = cv.fit_transform(corpus).toarray()
Y = df.iloc[:, -1].values
Y

array([0, 0, 1, ..., 1, 0, 1], dtype=int64)

In [25]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [26]:
nb_model = GaussianNB()
nb_model.fit(X_train,Y_train)

GaussianNB()

In [27]:
Y_predict = model.predict(X_test)

In [28]:
accuracy_score(Y_test, Y_predict)

0.5235109717868338

In [29]:
confusion_matrix = confusion_matrix(Y_test, Y_predict)
print(confusion_matrix)

[[ 67  84]
 [ 68 100]]


In [30]:
np.concatenate((Y_predict.reshape(len(Y_predict),1), Y_predict.reshape(len(Y_predict),1)),1)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1,